### ISSUE TITLE
没有Intel版本吗

### ISSUE THREAD

**Issue by cddehsy** [thep0y/alley#36]
没有Intel版本吗

这个ARM版本支持11和12吗？目前14能用。

**Comment by thep0y** [comment]
我只有一个 m2 的 Mac Mini，版本是 14，所以只编译了 aarch64，Intel 的编译后应该也能用，但 14 版本以下没有测试环境。

**Comment by thep0y** [comment]
https://github.com/thep0y/alley/releases/tag/v0.1.0-alpha.9 添加了 x86_64 版本，你试一下，如果可用的话就关闭 issue 吧，低版本的 macOS 兼容问题去开一个新的 issue。
